Pages/Cart.cshtml.cs
using HCI_Project.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using HCI_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.CodeAnalysis.Scripting;

namespace HCI_Project.Pages
{
    public class CartModel : PageModel
    {
        public List<Section> cart { get; set; }
        public List<Takeableclass> takeableclasses { get; set; }
        private readonly HCI_Project.registrationContext _context;
        public CartModel(HCI_Project.registrationContext context)
        {
            _context = context;
        }
        public async Task OnGet()
        {
            cart = SessionHelper.GetObjectFromJson<List<Section>>(HttpContext.Session, "cart");
            var classes = from m in _context.Takeableclasses select m;
            takeableclasses = await classes.ToListAsync();
        }

        public async Task<IActionResult> OnGetBuyNow(decimal id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Section>>(HttpContext.Session, "cart");
            var sections = from m in _context.Sections
                           select m;
            int i = 0;
            Section? section = null;
            foreach (var item in await sections.ToListAsync())
            {
                Console.WriteLine("item.Crn:" + item.Crn + "\n");
                Console.WriteLine("Cart Crn:" + id + "\n");
                if (item.Crn == id)
                {
                    i++;
                    section = item;
                    break;
                }
            }
            if (i == 0)
            {
                return RedirectToPage("Details");
            }

            if (section == null)
            {
                return RedirectToPage("Courses");
            }
            if (cart == null)
            {
                cart = new List<Section>();
                cart.Add((section));
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                int index = 0;
                foreach (Section item in cart)
                {
                    if (item.Crn == id)
                    {
                        index--;
                        break;
                    }
                }
                if (index == 0)
                {
                    cart.Add(section);
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("Cart");
        }
        public IActionResult OnGetDelete(decimal id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Section>>(HttpContext.Session, "cart");
            foreach (var item in cart)
            {
                if (item.Crn == id)
                {
                    cart.Remove(item);
                    break;
                }
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("Cart");
        }
    }
}

Pages/Courses/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using HCI_Project;
using HCI_Project.Models;

namespace HCI_Project.Pages.Courses
{
    public class CreateModel : PageModel
    {
        private readonly HCI_Project.registrationContext _context;

        public CreateModel(HCI_Project.registrationContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["Classid"] = new SelectList(_context.Takeableclasses, "Classid", "Classid");
            return Page();
        }

        [BindProperty]
        public Section Section { get; set; }
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Sections.Add(Section);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/Courses/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HCI_Project;
using HCI_Project.Models;

namespace HCI_Project.Pages.Courses
{
    public class DetailsModel : PageModel
    {
        private readonly HCI_Project.registrationContext _context;

        public DetailsModel(HCI_Project.registrationContext context)
        {
            _context = context;
        }
        public Section Section { get; set; }
 
 
        public async Task<IActionResult> OnGetAsync(decimal? id)
        {
            if (id == null || _context.Sections == null)
            {
                return NotFound();
            }
            var section = await _context.Sections.FirstOrDefaultAsync(m => m.Crn == id);
        
            if (section == null)
            {
                return NotFound();
            }
            else 
            {
                Section = section;
                var takeableclass = await _context.Takeableclasses.FirstOrDefaultAsync(m => m.Classid == Section.Classid);
                Section.Class = takeableclass;
            }
            return Page();
        }
    }
}

Pages/Courses/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using HCI_Project;
using HCI_Project.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.AccessControl;
using static Microsoft.Extensions.Logging.EventSource.LoggingEventSource;

public static class Extension
{
    public static bool Contains(this string source, string toCheck, StringComparison comp)
    {
        return source != null && toCheck != null && source.IndexOf(toCheck, comp) >= 0;
    }
}
namespace HCI_Project.Pages.Courses
{
    public class IndexModel : PageModel
    {
        private readonly HCI_Project.registrationContext _context;

        public IndexModel(HCI_Project.registrationContext context)
        {
            _context = context;
        }


        public IList<Section> Section { get;set; } = default!;
        public IList<Takeableclass> Class { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public string? SearchString { get; set; }
        [BindProperty(SupportsGet = true)]
        public int? CRN { get; set; }
        public async Task OnGetAsync()
        {
            var classes = from m in _context.Takeableclasses
                         select m;
            var sections = from m in _context.Sections
                           select m;
            if (!string.IsNullOrEmpty(SearchString))
            {
                classes = classes.Where(x => x.Classname.ToLower().Contains(SearchString.ToLower()));
            }
            if (!string.IsNullOrEmpty(CRN.ToString()))
            {
                 sections = sections.Where(s => s.Crn ==CRN);
                 
            }
            Class = await classes.ToListAsync();
            Section = await sections.ToListAsync();
        }
    }
}

Pages/Courses/Create.cshtml
@page
@model HCI_Project.Pages.Courses.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Section</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Section.Crn" class="control-label"></label>
                <input asp-for="Section.Crn" class="form-control" />
                <span asp-validation-for="Section.Crn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Section.Classid" class="control-label"></label>
                <select asp-for="Section.Classid" class ="form-control" asp-items="ViewBag.Classid"></select>
            </div>
            <div class="form-group">
                <label asp-for="Section.Prof" class="control-label"></label>
                <input asp-for="Section.Prof" class="form-control" />
                <span asp-validation-for="Section.Prof" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Section.Days" class="control-label"></label>
                <input asp-for="Section.Days" class="form-control" />
                <span asp-validation-for="Section.Days" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Section.Timeslot" class="control-label"></label>
                <input asp-for="Section.Timeslot" class="form-control" />
                <span asp-validation-for="Section.Timeslot" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Section.Locations" class="control-label"></label>
                <input asp-for="Section.Locations" class="form-control" />
                <span asp-validation-for="Section.Locations" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Section.Typeofclass" class="control-label"></label>
                <input asp-for="Section.Typeofclass" class="form-control" />
                <span asp-validation-for="Section.Typeofclass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/Courses/Details.cshtml
@page
@model HCI_Project.Pages.Courses.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Section</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Section.Crn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Section.Crn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Section.Prof)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Section.Prof)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Section.Days)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Section.Days)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Section.Timeslot)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Section.Timeslot)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Section.Locations)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Section.Locations)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Section.Typeofclass)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Section.Typeofclass)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Section.Class.Prefix)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Section.Class.Prefix)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Section.Class.Code)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Section.Class.Code)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Section.Class.Classname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Section.Class.Classname)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Index">Back to search</a>      
    &nbsp &nbsp &nbsp &nbsp
     <a asp-page-handler="CartAdd">Add to Cart </a>
    <br />&nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp &nbsp
    <a asp-page="../Cart" asp-page-handler="BuyNow" asp-route-id="@Model.Section.Crn"><img alt="cart" src="https://cdn-icons-png.flaticon.com/512/263/263142.png" height="50x"> </a>
</div>

Pages/Courses/Index.cshtml
@page
@model HCI_Project.Pages.Courses.IndexModel

@{
    ViewData["Title"] = "Course Selection";
}

<h1>Course Selection</h1>

<form>
    <label for="Class">Search by Class Name:</label><br />
    <input type="text"asp-for="SearchString" />
    <input type="submit" value="Search" /><br />
</form>

<form>
    <label for="CourseID">Search by Course ID:</label><br />
    <input type="text" asp-for="CRN" />
    <input type="submit" value="Search" /><br />
</form>

<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Section[0].Class)
          
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Section[0].Days)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Section[0].Timeslot)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Section[0].Locations)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Section[0].Typeofclass)
            </th>
            <th>
            
                @Html.DisplayNameFor(model => model.Section[0].Prof)
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Section) {
            int i = 0;
            @foreach (var item1 in Model.Class) {
              if (item1.Classid == item.Classid) {
                    i++;
                    break;
                }  
            }
            if (i == 0) {
                continue;
            }
            <tr>
            <td>
                    @foreach (var item1 in Model.Class)
                    {
                        @if (item1.Classid == item.Classid)
                        {
                            @Html.DisplayFor(modelItem => item1.Classname)
                        }
                    }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Days)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Timeslot)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Locations)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Typeofclass)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Prof)
               
            </td>
            <td>
                <a asp-page="./Details" asp-route-id="@item.Crn">Details</a>
            </td>
            <td>
               <a asp-page="../Cart" asp-page-handler="BuyNow" asp-route-id="@item.Crn"><img alt="cart" src="https://cdn-icons-png.flaticon.com/512/263/263142.png" height="30"></a>
            </td>
        </tr>
}
    </tbody>
</table>